config/routes.rb
Rails.application.routes.draw do
  resources :pforms
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :otcs
  resources :ods
  resources :mjs
  resources :alcohols
  resources :cigarettes
  resources :refbs
  resources :refas
  resources :pregs
  resources :cparents
  resources :discharges
  resources :mhealths
  resources :rhealths
  resources :wks
  resources :grades
  resources :eds
  resources :insurances
  resources :races
  resources :employments
  resources :rsources
  resources :states
  resources :notes
  devise_for :users
  resources :notes
  resources :genders
  get 'home/index'
  get 'testp/test'

  
  
  resources :clients do
  resources :notes, except: [:show, :index]
end

   root 'home#index'

end

app/models/alcohol.rb
class Alcohol < ActiveRecord::Base
    has_many :clients
end

app/models/client.rb
class Client < ActiveRecord::Base
    mount_uploader :image, ImageUploader

    belongs_to :gender
    has_many   :notes
    belongs_to :state
    belongs_to :rsource
    belongs_to :employment
    belongs_to :race
    belongs_to :insurance
    belongs_to :ed
    belongs_to :grade
    belongs_to :cigarette
    belongs_to :alcohol
    belongs_to :mj
    belongs_to :od
    #belongs_to :mhealth_sub
    #belongs_to :school
    #belongs_to :grad
    belongs_to :wk
    #belongs_to :text_Rs
    #belongs_to :text_id
    #belongs_to :truma
    belongs_to :college
    has_and_belongs_to_many :rhealths
    has_and_belongs_to_many :mhealths
    #has_and_belongs_to_many :dischages
    has_and_belongs_to_many :cparents
    has_and_belongs_to_many :pregs
    #has_and_belongs_to_many :refferal
    has_and_belongs_to_many :refas
    has_and_belongs_to_many :refbs
    
    
    validates :firstName, :lastName, presence: true
    validates :phone, format: { with: /\A\(\d{3}\) \d{3}-\d{4}\z/,
    message: "must be in the format (123) 456-7890" }
end

app/models/cnote.rb
class Cnote < ActiveRecord::Base
    belongs_to :user
    belongs_to :client
end

app/models/college.rb
class College < ActiveRecord::Base
    has_many :clients
end

app/models/cparent.rb
class Cparent < ActiveRecord::Base
    has_and_belongs_to_many :clients
end

app/models/ed.rb
class Ed < ActiveRecord::Base
    has_many :clients
end

app/models/gender.rb
class Gender < ActiveRecord::Base
    has_many :clients
end

app/models/grade.rb
class Grade < ActiveRecord::Base
    has_many :clients
end

app/models/mhealth.rb
class Mhealth < ActiveRecord::Base
    has_and_belongs_to_many :clients
end

app/models/mj.rb
class Mj < ActiveRecord::Base
    has_many :clients
end

app/models/note.rb
class Note < ActiveRecord::Base
   belongs_to :user
   belongs_to :client
end

app/models/od.rb
class Od < ActiveRecord::Base
    has_many :clients
end

app/models/otc.rb
class Otc < ActiveRecord::Base
end

app/models/pform.rb
class Pform < ActiveRecord::Base
end

app/models/preg.rb
class Preg < ActiveRecord::Base
    has_and_belongs_to_many :cleints
end

app/models/race.rb
class Race < ActiveRecord::Base
    has_many :clients
end

app/models/refa.rb
class Refa < ActiveRecord::Base
    has_and_belongs_to_many :clients
end

app/models/refb.rb
class Refb < ActiveRecord::Base
    has_and_belongs_to_many :clients
end

app/models/state.rb
class State < ActiveRecord::Base
    has_many :clients
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
         has_many :notes # To delete notes when user is deleted replace with "has_many : notes, dependent: :destroy"
         
         validates :first_name, :last_name, presence: true
end

app/models/wk.rb
class Wk < ActiveRecord::Base
    has_many :clients
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  before_action :set_client
  before_action :check_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /notes
  # GET /notes.json
  def index
     #@notes = Note.order("created_at DESC")
     #@notes = Note.all.uniq.order("created_at DESC")
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
    #@notes = Note.order("created_at DESC")
    #@notes = Note.all.uniq.order("created_at DESC")
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id #This like added the current user ID into the user_id filed in when a note is created.
    @note.client_id = @client.id

    respond_to do |format|
      if @note.save
        format.html { redirect_to @client, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to client_path(@client), notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to client_path(@client), notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:client_id])
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end
    
    def check_user
      unless (@note.user == current_user) || (current_user.admin?)
        redirect_to root_url, alert: "Sorry, this not belongs to someone else"
      end
    end
    
   # def set_client
    #  @client = Client.find(params[:client_id])
    #end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:comment)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_for([@client, @note]) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment, rows: 10, cols: 120 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path(@note) %>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Notes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% raw @notes.each do |note| %>
      <tr>
        <td><%= note.title %></td>
        <td><%= note.body %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<h2 class"note">New Note for <small><%= @client.firstName %> <%=@client.lastName %></small></h2>

<%= render 'form' %>

<%= link_to 'Back', client_path(@client) %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment:</strong>
  <%= raw @note.comment %>
</p>

<%= link_to "Write A Note", new_client_note_path(@client), class: "btn btn-primary" %>
<%= link_to 'Edit', edit_note_path(@note) class: "btn btn-primary" %> |
<%= link_to 'Back', notes_path, class: "btn btn-primary" %>