config/routes.rb
Rails.application.routes.draw do
  resources :pforms
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :otcs
  resources :ods
  resources :mjs
  resources :alcohols
  resources :cigarettes
  resources :refbs
  resources :refas
  resources :pregs
  resources :cparents
  resources :discharges
  resources :mhealths
  resources :rhealths
  resources :wks
  resources :grades
  resources :eds
  resources :insurances
  resources :races
  resources :employments
  resources :rsources
  resources :states
  resources :notes
  devise_for :users
  resources :notes
  resources :genders
  get 'home/index'
  get 'testp/test'

  
  
  resources :clients do
  resources :notes, except: [:show, :index]
end

   root 'home#index'

end

app/models/alcohol.rb
class Alcohol < ActiveRecord::Base
    has_many :clients
end

app/models/client.rb
class Client < ActiveRecord::Base
    mount_uploader :image, ImageUploader

    belongs_to :gender
    has_many   :notes
    belongs_to :state
    belongs_to :rsource
    belongs_to :employment
    belongs_to :race
    belongs_to :insurance
    belongs_to :ed
    belongs_to :grade
    belongs_to :cigarette
    belongs_to :alcohol
    belongs_to :mj
    belongs_to :od
    #belongs_to :mhealth_sub
    #belongs_to :school
    #belongs_to :grad
    belongs_to :wk
    #belongs_to :text_Rs
    #belongs_to :text_id
    #belongs_to :truma
    belongs_to :college
    has_and_belongs_to_many :rhealths
    has_and_belongs_to_many :mhealths
    #has_and_belongs_to_many :dischages
    has_and_belongs_to_many :cparents
    has_and_belongs_to_many :pregs
    #has_and_belongs_to_many :refferal
    has_and_belongs_to_many :refas
    has_and_belongs_to_many :refbs
    
    
    validates :firstName, :lastName, presence: true
    validates :phone, format: { with: /\A\(\d{3}\) \d{3}-\d{4}\z/,
    message: "must be in the format (123) 456-7890" }
end

app/models/cnote.rb
class Cnote < ActiveRecord::Base
    belongs_to :user
    belongs_to :client
end

app/models/college.rb
class College < ActiveRecord::Base
    has_many :clients
end

app/models/cparent.rb
class Cparent < ActiveRecord::Base
    has_and_belongs_to_many :clients
end

app/models/ed.rb
class Ed < ActiveRecord::Base
    has_many :clients
end

app/models/gender.rb
class Gender < ActiveRecord::Base
    has_many :clients
end

app/models/grade.rb
class Grade < ActiveRecord::Base
    has_many :clients
end

app/models/insurance.rb
class Insurance < ActiveRecord::Base
    has_many :clients
end

app/models/mj.rb
class Mj < ActiveRecord::Base
    has_many :clients
end

app/models/note.rb
class Note < ActiveRecord::Base
   belongs_to :user
   belongs_to :client
end

app/models/od.rb
class Od < ActiveRecord::Base
    has_many :clients
end

app/models/otc.rb
class Otc < ActiveRecord::Base
end

app/models/pform.rb
class Pform < ActiveRecord::Base
end

app/models/preg.rb
class Preg < ActiveRecord::Base
    has_and_belongs_to_many :cleints
end

app/models/race.rb
class Race < ActiveRecord::Base
    has_many :clients
end

app/models/refa.rb
class Refa < ActiveRecord::Base
    has_and_belongs_to_many :clients
end

app/models/refb.rb
class Refb < ActiveRecord::Base
    has_and_belongs_to_many :clients
end

app/models/state.rb
class State < ActiveRecord::Base
    has_many :clients
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
         has_many :notes # To delete notes when user is deleted replace with "has_many : notes, dependent: :destroy"
         
         validates :first_name, :last_name, presence: true
end

app/models/wk.rb
class Wk < ActiveRecord::Base
    has_many :clients
end

app/controllers/insurances_controller.rb
class InsurancesController < ApplicationController
  before_action :set_insurance, only: [:show, :edit, :update, :destroy]

  # GET /insurances
  # GET /insurances.json
  def index
    @insurances = Insurance.all
  end

  # GET /insurances/1
  # GET /insurances/1.json
  def show
  end

  # GET /insurances/new
  def new
    @insurance = Insurance.new
  end

  # GET /insurances/1/edit
  def edit
  end

  # POST /insurances
  # POST /insurances.json
  def create
    @insurance = Insurance.new(insurance_params)

    respond_to do |format|
      if @insurance.save
        format.html { redirect_to @insurance, notice: 'Insurance was successfully created.' }
        format.json { render :show, status: :created, location: @insurance }
      else
        format.html { render :new }
        format.json { render json: @insurance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /insurances/1
  # PATCH/PUT /insurances/1.json
  def update
    respond_to do |format|
      if @insurance.update(insurance_params)
        format.html { redirect_to @insurance, notice: 'Insurance was successfully updated.' }
        format.json { render :show, status: :ok, location: @insurance }
      else
        format.html { render :edit }
        format.json { render json: @insurance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /insurances/1
  # DELETE /insurances/1.json
  def destroy
    @insurance.destroy
    respond_to do |format|
      format.html { redirect_to insurances_url, notice: 'Insurance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_insurance
      @insurance = Insurance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def insurance_params
      params.require(:insurance).permit(:name)
    end
end

app/helpers/insurances_helper.rb
module InsurancesHelper
end

app/views/insurances/_form.html.erb
<%= form_for(@insurance) do |f| %>
  <% if @insurance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@insurance.errors.count, "error") %> prohibited this insurance from being saved:</h2>

      <ul>
      <% @insurance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/insurances/edit.html.erb
<h1>Editing Insurance</h1>

<%= render 'form' %>

<%= link_to 'Show', @insurance %> |
<%= link_to 'Back', insurances_path %>

app/views/insurances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Insurances</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @insurances.each do |insurance| %>
      <tr>
        <td><%= insurance.name %></td>
        <td><%= link_to 'Show', insurance %></td>
        <td><%= link_to 'Edit', edit_insurance_path(insurance) %></td>
        <td><%= link_to 'Destroy', insurance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Insurance', new_insurance_path %>

app/views/insurances/new.html.erb
<h1>New Insurance</h1>

<%= render 'form' %>

<%= link_to 'Back', insurances_path %>

app/views/insurances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @insurance.name %>
</p>

<%= link_to 'Edit', edit_insurance_path(@insurance) %> |
<%= link_to 'Back', insurances_path %>